### PR TITLE
Adding new dataset of label to the performance testing

### PR DESCRIPTION
**Pull request by SamuelPelletierEvraire**

### CODE REVIEW

**Review by k-allagbe — APPROVED** [review]
Impressive. LGTM.

**Review by Endlessflow — COMMENTED** [review]
I used these successfully. I think more in-depth insights on the ground truth dataset will have to wait until we aggregate data from the performance assessment.

One element of confusion is that there are about 30 ish label but the folder names go all the way to 50 ish. Can be confusing.

If the mismatch with the label folder names is deemed acceptable this should be fine to merge.

**Comment by k-allagbe** [comment]
> I think more in-depth insights on the ground truth dataset will have to wait until we aggregate data from the performance assessment.

Okay. In the meantime if you notice anything suspect like the numbering discrepancy you mentioned, please request a change.

**Comment by Endlessflow** [comment]
I got @SamuelPelletierEvraire 's permission to fix the numbering discrepancy and merge this. 
Everything is taken care of so I'm going to go ahead and merge the PR.

**Pull request merged**
