### PR TITLE
Issue #19: Use the pydantic schema inside the prompt

### PR DESCRIPTION
**Pull request by snakedye**
Currently it's not possible to use **json_schema** as the `response_format`.

In the meantime, I added an additional input field to the DSPy prompt that accepts a JSON schema. Namely the one from pydantic. Since we can't guarantee at this level that the output will always fit the schema, more testing is necessary.

Related to #19

### CODE REVIEW

**Review by k-allagbe — DISMISSED** [review]
Tested, works as expected. Fixed some pydantic validation errors.

**Review by k-allagbe — COMMENTED** [review]
Tested this image:
image

Results:
```json
{
  "company_name": null,
  "company_address": null,
  "company_website": "lesgranulaines.com",
  "company_phone_number": null,
  "manufacturer_name": null,
  "manufacturer_address": null,
  "manufacturer_website": null,
  "manufacturer_phone_number": null,
  "fertiliser_name": "ALL - PURPOSE NATURAL FERTILISER",
  "registration_number": null,
  "lot_number": "L-1",
  "weight": [],
  "density": null,
  "volume": null,
  "npk": "10-0-4",
  "guaranteed_analysis": [
    { "nutrient": "Total nitrogen (N)", "value": "10", "unit": null },
    { "nutrient": "Soluble potash (K20)", "value": "4", "unit": null },
    { "nutrient": "Organic matter", "value": "61.5", "unit": null }
  ],
  "warranty": null,
  "cautions_en": ["Wash your hands after use.", "Keep away from children."],
  "instructions_en": [
    "1 application per season",
    "Garden: incorporate 150 to 200 grams of Granu-Laines per m2 into first top 10 cm of soil before seeding.",
    "Tomato: incorporate 150 grams underneath each plant.",
    "Cucumber and squash: incorporate 100 grams underneath each plant.",
    "For cultivating in pots or large containers, mix in 50 grams of Granu-Laines per 4 liters of soil.",
    "For any questions, please contact your garden center."
  ],
  "micronutrients_en": [],
  "ingredients_en": [
    { "nutrient": "Ingredients", "value": "100", "unit": null }
  ],
  "specifications_en": [
    { "humidity": "14.8%", "ph": null, "solubility": null }
  ],
  "first_aid_en": [],
  "cautions_fr": [
    "Se laver les mains après chaque utilisation.",
    "Garder hors de la portée des enfants."
  ],
  "instructions_fr": [
    "1 seule application par saison",
    "Pour votre potager, incorporer 150 à 200g de Granu-Laines par m2 de sol.",
    "Tomate: incorporer 150g sous chaque plant.",
    "Concombre et courge: incorporer 100g sous chaque plante.",
    "Pour la culture en pot ou en bac, incorporer 50g par 4 litres de terre.",
    "Et en cas de besoin, renseignez-vous à votre centre jardin."
  ],
  "micronutrients_fr": [],
  "ingredients_fr": [
    { "nutrient": "Ingrédients", "value": "100", "unit": null }
  ],
  "specifications_fr": [
    { "humidity": "14.8%", "ph": null, "solubility": null }
  ],
  "first_aid_fr": []
}

```

The ingredients are not quite right, there are some missing units...


I tried annotating the models. Like this:
```python
import re

from pydantic import BaseModel, Field, field_validator, model_validator


class npkError(ValueError):
    pass


def extract_first_number(string):
    if string is not None:
        match = re.search(r"\d+(\.\d+)?", string)
        if match:
            return match.group()
    return None


class NutrientValue(BaseModel):
    nutrient: str = Field(
        ...,
        description="The name of the nutrient or ingredient",
        examples=["Iron (Fe)", "Zinc (Zn)", "Bone meal"],
    )
    value: str | None = Field(
        None,
        description="The amount or concentration of the nutrient",
        examples=["0.10", "5"],
    )
    unit: str | None = Field(
        None,
        description="The unit of measurement for the value",
        examples=["%", "mg/kg"],
    )

    @field_validator("value", mode="before", check_fields=False)
    def convert_value(cls, v):
        if isinstance(v, (int, float)):
            return str(v)
        return extract_first_number(v)


class Value(BaseModel):
    value: str | None = Field(
        None,
        description="The numerical value of the measurement",
        examples=["25", "55", "1.2", "20.8"],
    )
    unit: str | None = Field(
        None, description="The unit of measurement", examples=["kg", "lb", "g/cm", "L"]
    )

    @field_validator("value", mode="before", check_fields=False)
    def convert_value(cls, v):
        if isinstance(v, (int, float)):
            return str(v)
        return extract_first_number(v)


class Specification(BaseModel):
    humidity: str | None = Field(
        ...,
        alias="humidity",
        description="The humidity level, typically as a percentage",
        examples=["10"],
    )
    ph: str | None = Field(
        ...,
        alias="ph",
        description="The pH level, indicating acidity or alkalinity",
        examples=["6.5"],
    )
    solubility: str | None = Field(
        None,
        description="The solubility value, often measured in grams per liter",
        examples=["100"],
    )

    @field_validator("humidity", "ph", "solubility", mode="before", check_fields=False)
    def convert_specification_values(cls, v):
        if isinstance(v, (int, float)):
            return str(v)
        return v


class FertilizerInspection(BaseModel):
    company_name: str | None = Field(
        None, description="Name of the company", examples=["GreenGrow Fertilizers Inc."]
    )
    company_address: str | None = Field(
        None,
        description="Address of the company",
        examples=["123 Greenway Blvd, Springfield IL 62701 USA"],
    )
    company_website: str | None = Field(
        None,
        description="Website of the company",
        examples=["www.greengrowfertilizers.com"],
    )
    company_phone_number: str | None = Field(
        None, description="Phone number of the company", examples=["+1 800 555 0199"]
    )
    manufacturer_name: str | None = Field(
        None,
        description="Name of the manufacturer",
        examples=["AgroTech Industries Ltd."],
    )
    manufacturer_address: str | None = Field(
        None,
        description="Address of the manufacturer",
        examples=["456 Industrial Park Rd, Oakville ON L6H 5V4 Canada"],
    )
    manufacturer_website: str | None = Field(
        None,
        description="Website of the manufacturer",
        examples=["www.agrotechindustries.com"],
    )
    manufacturer_phone_number: str | None = Field(
        None,
        description="Phone number of the manufacturer",
        examples=["+1 416 555 0123"],
    )
    fertiliser_name: str | None = Field(
        None, description="Name of the fertiliser", examples=["SuperGrow 20-20-20"]
    )
    registration_number: str | None = Field(
        None,
        description="Registration number of the fertiliser",
        examples=["F12345678"],
    )
    lot_number: str | None = Field(
        None, description="Lot number of the fertiliser", examples=["L987654321"]
    )
    weight: list[Value] = Field(
        default_factory=list,
        description="List of weights with units",
        examples=[[{"value": "25", "unit": "kg"}, {"value": "55", "unit": "lb"}]],
    )
    density: Value | None = Field(
        None,
        description="Density of the fertiliser",
        examples=[{"value": "1.2", "unit": "g/cm"}],
    )
    volume: Value | None = Field(
        None,
        description="Volume of the fertiliser",
        examples=[{"value": "20.8", "unit": "L"}],
    )
    npk: str | None = Field(
        None, description="N-P-K ratio of the fertiliser", examples=["20-20-20"]
    )
    guaranteed_analysis: list[NutrientValue] = Field(
        default_factory=list,
        description="Guaranteed analysis of primary nutrients",
        examples=[
            [
                {"nutrient": "Total Nitrogen (N)", "value": "20", "unit": "%"},
                {"nutrient": "Available Phosphate (P2O5)", "value": "20", "unit": "%"},
                {"nutrient": "Soluble Potash (K2O)", "value": "20", "unit": "%"},
            ]
        ],
    )
    warranty: str | None = Field(
        None,
        description="Warranty information",
        examples=["Guaranteed analysis of nutrients."],
    )
    cautions_en: list[str] = Field(
        default_factory=list,
        description="List of caution statements in English",
        examples=[
            ["Keep out of reach of children.", "Avoid contact with skin and eyes."]
        ],
    )
    instructions_en: list[str] = Field(
        default_factory=list,
        description="Usage instructions in English",
        examples=[
            [
                "1. Dissolve 50g in 10L of water.",
                "2. Apply every 2 weeks.",
                "3. Store in a cool, dry place.",
            ]
        ],
    )
    micronutrients_en: list[NutrientValue] = Field(
        default_factory=list,
        description="List of micronutrients in English",
        examples=[
            [
                {"nutrient": "Iron (Fe)", "value": "0.10", "unit": "%"},
                {"nutrient": "Zinc (Zn)", "value": "0.05", "unit": "%"},
                {"nutrient": "Manganese (Mn)", "value": "0.05", "unit": "%"},
            ]
        ],
    )
    ingredients_en: list[NutrientValue] = Field(
        default_factory=list,
        description="List of ingredients in English",
        examples=[
            [
                {"nutrient": "Bone meal", "value": "5", "unit": "%"},
                {"nutrient": "Seaweed extract", "value": "3", "unit": "%"},
                {"nutrient": "Humic acid", "value": "2", "unit": "%"},
                {"nutrient": "Clay", "value": "", "unit": ""},
                {"nutrient": "Sand", "value": "", "unit": ""},
                {"nutrient": "Perlite", "value": "", "unit": ""},
            ]
        ],
    )
    specifications_en: list[Specification] = Field(
        default_factory=list,
        description="Specifications of the product in English",
        examples=[[{"humidity": "10", "ph": "6.5", "solubility": "100"}]],
    )
    first_aid_en: list[str] = Field(
        default_factory=list,
        description="First aid instructions in English",
        examples=[
            [
                "In case of contact with eyes, rinse immediately with plenty of water and seek medical advice."
            ]
        ],
    )
    cautions_fr: list[str] = Field(
        default_factory=list,
        description="List of caution statements in French",
        examples=[
            [
                "Tenir hors de portée des enfants.",
                "Éviter le contact avec la peau et les yeux.",
            ]
        ],
    )
    instructions_fr: list[str] = Field(
        default_factory=list,
        description="Usage instructions in French",
        examples=[
            [
                "1. Dissoudre 50g dans 10L d'eau.",
                "2. Appliquer toutes les 2 semaines.",
                "3. Conserver dans un endroit frais et sec.",
            ]
        ],
    )
    micronutrients_fr: list[NutrientValue] = Field(
        default_factory=list,
        description="List of micronutrients in French",
        examples=[
            [
                {"nutrient": "Fer (Fe)", "value": "0.10", "unit": "%"},
                {"nutrient": "Zinc (Zn)", "value": "0.05", "unit": "%"},
                {"nutrient": "Manganèse (Mn)", "value": "0.05", "unit": "%"},
            ]
        ],
    )
    ingredients_fr: list[NutrientValue] = Field(
        default_factory=list,
        description="List of ingredients in French",
        examples=[
            [
                {"nutrient": "Farine d'os", "value": "5", "unit": "%"},
                {"nutrient": "Extrait d'algues", "value": "3", "unit": "%"},
                {"nutrient": "Acide humique", "value": "2", "unit": "%"},
                {"nutrient": "Argile", "value": "", "unit": ""},
                {"nutrient": "Sable", "value": "", "unit": ""},
                {"nutrient": "Perlite", "value": "", "unit": ""},
            ]
        ],
    )
    specifications_fr: list[Specification] = Field(
        default_factory=list,
        description="Specifications of the product in French",
        examples=[[{"humidity": "10", "ph": "6.5", "solubility": "100"}]],
    )
    first_aid_fr: list[str] = Field(
        default_factory=list,
        description="First aid instructions in French",
        examples=[
            [
                "En cas de contact avec les yeux, rincer immédiatement à grande eau et consulter un médecin."
            ]
        ],
    )

    @field_validator("density", "volume", mode="before", check_fields=False)
    def convert_values(cls, v):
        if isinstance(v, (int, float)):
            return str(v)
        return v

    @field_validator("npk", mode="before")
    def validate_npk(cls, v):
        if v is not None:
            pattern = re.compile(r"^(\d+(\.\d+)?-\d+(\.\d+)?-\d+(\.\d+)?)?$")
            if not pattern.match(v):
                raise npkError('npk must be in the format "number-number-number"')
        return v

    @model_validator(mode="before")
    def replace_none_with_empty_list(cls, values):
        fields_to_check = [
            "cautions_en",
            "first_aid_en",
            "cautions_fr",
            "first_aid_fr",
            "instructions_en",
            "micronutrients_en",
            "ingredients_en",
            "specifications_en",
            "instructions_fr",
            "micronutrients_fr",
            "ingredients_fr",
            "specifications_fr",
            "guaranteed_analysis",
        ]
        for field in fields_to_check:
            if values.get(field) is None:
                values[field] = []
        return values

    class Config:
        populate_by_name = True

```


Results:
```json
{
  "company_name": null,
  "company_address": null,
  "company_website": "lesgranulaines.com",
  "company_phone_number": null,
  "manufacturer_name": null,
  "manufacturer_address": null,
  "manufacturer_website": null,
  "manufacturer_phone_number": null,
  "fertiliser_name": "Granu-Laines",
  "registration_number": null,
  "lot_number": "L-1",
  "weight": [],
  "density": null,
  "volume": null,
  "npk": "10-0-4",
  "guaranteed_analysis": [
    { "nutrient": "Total nitrogen (N)", "value": "10", "unit": "%" },
    { "nutrient": "Soluble potash (K20)", "value": "4", "unit": "%" },
    { "nutrient": "Organic matter", "value": "61.5", "unit": "%" },
    { "nutrient": "Maximum moisture content", "value": "14.8", "unit": "%" }
  ],
  "warranty": null,
  "cautions_en": ["Wash your hands after use.", "Keep away from children."],
  "instructions_en": [
    "Garden: incorporate 150 to 200 grams of Granu-Laines per m2 into first top 10 cm of soil before seeding.",
    "Tomato: incorporate 150 grams underneath each plant.",
    "Cucumber and squash: incorporate 100 grams underneath each plant.",
    "For cultivating in pots or large containers, mix in 50 grams of Granu-Laines per 4 liters of soil.",
    "For any questions, please contact your garden center."
  ],
  "micronutrients_en": [],
  "ingredients_en": [
    { "nutrient": "100% raw sheep wool", "value": null, "unit": null }
  ],
  "specifications_en": [],
  "first_aid_en": [],
  "cautions_fr": [
    "Se laver les mains après chaque utilisation.",
    "Garder hors de la portée des enfants."
  ],
  "instructions_fr": [
    "Pour votre potager, incorporer 150 à 200g de Granu-Laines par m2 de sol.",
    "Tomate: incorporer 150g sous chaque plant.",
    "Concombre et courge: incorporer 100g sous chaque plante.",
    "Pour la culture en pot ou en bac, incorporer 50g par 4 litres de terre.",
    "Et en cas de besoin, renseignez-vous à votre centre jardin."
  ],
  "micronutrients_fr": [],
  "ingredients_fr": [
    { "nutrient": "100% laine brute de moutons", "value": null, "unit": null }
  ],
  "specifications_fr": [],
  "first_aid_fr": []
}

```

A lot better in my opinion, but not perfect. Note that `{ "nutrient": "100% raw sheep wool", "value": null, "unit": null }` could have been `{ "nutrient": "raw sheep wool", "value": "100", "unit": "%" }`

**Comment by snakedye** [comment]
@k-allagbe It's impossible to have an accuracy of a 100% anyway. It will never extract everything but this looks promising.

The annotations should move into a different PR because it goes above the scope of this issue (minimizing a fatal error ie the schema being invalid). It still might have an impact on the performance which why I wanted @Endlessflow approval. 

The change you propose would require the performance testing framework to assess the real gain. With more tokens we're not necessarily guaranteed a better result in all cases.

**Comment by Endlessflow** [comment]
I think it might be a good idea to open a (draft) issue for your suggested change. @k-allagbe. Once we are done with the framework to test the pipeline, we'll be in a better position to evaluate the performance gain or loss.

**Comment by k-allagbe** [comment]
@snakedye @Endlessflow, I agree. I will move this to a draft issue. Please don't mind me.

**Review by Endlessflow — COMMENTED** [review]
It works as intended on paper. I am not sure about impact on performance though.
@k-allagbe We can either merge this now and hope the performance is better with this method and we dont have to revert to our previous method later.
Or we can hold off on merging this for now and mark the issue as blocked on the project board and once we have the results of the performance test we can decide if it is ok to merge it.

**Comment by k-allagbe** [comment]
> It works as intended on paper. I am not sure about impact on performance though. @k-allagbe We can either merge this now and hope the performance is better with this method and we dont have to revert to our previous method later. Or we can hold off on merging this for now and mark the issue as blocked on the project board and once we have the results of the performance test we can decide if it is ok to merge it.

We can always work on performance later. Better a slightly slower but errorless product. What do you think?

**Review by Endlessflow — APPROVED** [review]
Alright we can merge it then 👍

**Pull request merged**
